import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("health", "routes/health.ts"),
  route("hall", "routes/hall.tsx"),
  route("rooms/:room", "routes/room.tsx"),
  route("archive", "routes/archive.tsx"),
  route("archive/:slug", "routes/case-study.tsx"),
  route("projects", "routes/projects.tsx"),
  route("projects/new", "routes/project-new.tsx"),
  route("projects/manage", "routes/project-manage.tsx"),
  route("projects/:slug/edit", "routes/project-edit.tsx"),
  route("projects/:slug", "routes/project-detail.tsx"),
  route("events", "routes/events.tsx"),
  route("events/new", "routes/event-new.tsx"),
  route("events/manage", "routes/event-manage.tsx"),
  route("events/:slug/edit", "routes/event-edit.tsx"),
  route("events/:slug", "routes/event-detail.tsx"),
  route("login", "routes/login.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("register", "routes/register.tsx"),
  route("membership/check-email", "routes/membership-check-email.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("admin/applications", "routes/admin-applications.tsx"),
  route("admin/interests", "routes/admin-interests.tsx"),
  route("admin/moderation", "routes/admin-moderation.tsx"),
  route("notifications", "routes/notifications.tsx"),
  route("connections", "routes/connections.tsx"),
  route("settings/telegram", "routes/telegram-settings.tsx"),
  route("integrations/telegram/webhook", "routes/telegram-webhook.ts"),
  route("report", "routes/report.tsx"),
  route("logout", "routes/logout.tsx"),
  route("app", "routes/dashboard.tsx"),
  route("profiles/:username", "routes/profile.tsx"),
] satisfies RouteConfig;
