import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("health", "routes/health.ts"),
  route("__test__/personas/:persona", "routes/test-persona.ts"),
  route("__test__/launch-security/:action", "routes/test-launch-security.ts"),
  route("__test__/opportunities/:action", "routes/test-opportunities.ts"),
  route(
    "__test__/opportunity-documents/:action",
    "routes/test-opportunity-documents.ts",
  ),
  route("hall", "routes/hall.tsx"),
  route("rooms/:room", "routes/room.tsx"),
  route("archive", "routes/archive.tsx"),
  route("archive/:slug", "routes/case-study.tsx"),
  route("projects", "routes/projects.tsx"),
  route("projects/new", "routes/project-new.tsx"),
  route("projects/manage", "routes/project-manage.tsx"),
  route("projects/:slug/edit", "routes/project-edit.tsx"),
  route("projects/:slug/needs", "routes/project-needs.tsx"),
  route("projects/:slug/opportunity", "routes/project-opportunity.tsx"),
  route("projects/:slug/opportunity/manage", "routes/opportunity-manage.tsx"),
  route("projects/:slug/diligence", "routes/project-diligence.tsx"),
  route("projects/:slug/documents/:documentId", "routes/project-document.ts"),
  route("projects/:slug", "routes/project-detail.tsx"),
  route("projects/:slug/campaigns/new", "routes/campaign-new.tsx"),
  route("deals", "routes/deals.tsx"),
  route("deals/:dealSlug", "routes/deal-room.tsx"),
  route("campaigns", "routes/campaigns.tsx"),
  route("campaigns/:slug", "routes/campaign-detail.tsx"),
  route("campaigns/:slug/work", "routes/campaign-workspace.tsx"),
  route("campaigns/:slug/settlement", "routes/iio-settlement.tsx"),
  route("events", "routes/events.tsx"),
  route("events/new", "routes/event-new.tsx"),
  route("events/manage", "routes/event-manage.tsx"),
  route("events/:slug/edit", "routes/event-edit.tsx"),
  route("events/:slug", "routes/event-detail.tsx"),
  route("login", "routes/login.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("register", "routes/register.tsx"),
  route("membership", "routes/membership.tsx"),
  route("membership/check-email", "routes/membership-check-email.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("admin/operations", "routes/admin-operations.tsx"),
  route("admin/production", "routes/admin-production.tsx"),
  route("admin/resilience", "routes/admin-resilience.tsx"),
  route("admin/campaign-operations", "routes/admin-campaign-operations.tsx"),
  route("admin/launch-gate", "routes/admin-launch-gate.tsx"),
  route("admin/applications", "routes/admin-applications.tsx"),
  route("admin/interests", "routes/admin-interests.tsx"),
  route("admin/moderation", "routes/admin-moderation.tsx"),
  route("admin/team", "routes/admin-team.tsx"),
  route("admin/verifications", "routes/admin-verifications.tsx"),
  route("admin/opportunities", "routes/admin-opportunities.tsx"),
  route(
    "admin/opportunities/operations",
    "routes/admin-opportunity-operations.tsx",
  ),
  route(
    "admin/opportunities/documents",
    "routes/admin-opportunity-documents.tsx",
  ),
  route("admin/campaigns", "routes/admin-campaigns.tsx"),
  route("admin/integrations/google", "routes/admin-google-integration.tsx"),
  route("admin/iio/:slug", "routes/admin-iio-detail.tsx"),
  route("admin/iio/:slug/export.csv", "routes/admin-iio-export.ts"),
  route("admin/iio/:slug/settlement.csv", "routes/iio-settlement-export.ts"),
  route("integrations/google/callback", "routes/google-oauth-callback.ts"),
  route("notifications", "routes/notifications.tsx"),
  route("connections", "routes/connections.tsx"),
  route("members", "routes/members.tsx"),
  route("settings/account", "routes/account-settings.tsx"),
  route("settings/account/export", "routes/account-export.ts"),
  route("settings/investor", "routes/investor-settings.tsx"),
  route("settings/telegram", "routes/telegram-settings.tsx"),
  route("integrations/telegram/webhook", "routes/telegram-webhook.ts"),
  route("report", "routes/report.tsx"),
  route("logout", "routes/logout.tsx"),
  route("app", "routes/dashboard.tsx"),
  route("profiles/:username", "routes/profile.tsx"),
  route("media/profile/:username", "routes/profile-photo.ts"),
  route("privacy", "routes/legal.tsx"),
  route("terms", "routes/terms.tsx"),
  route("community-guidelines", "routes/community-guidelines.tsx"),
  route("contact", "routes/contact.tsx"),
  route("admin/contact", "routes/admin-contact.tsx"),
] satisfies RouteConfig;
